### ISSUE TITLE
[feature] set a timeout to limit a command maximum time

### ISSUE THREAD

**Issue by gre** [gre/playCLI#4]

**Comment by gre** [comment]
This only make sense for the CLI.consume because for others a Done can be sent to the iteratee of pipe and enumerate. 
(Should I change the signature of consume to return an iteratee instead, or with an apply?)

**Comment by gre** [comment]
Finally, CLI.consume returns an Iteratee.

EOF can be gived in iteratee.feed to terminated the command.

**Comment by gre** [comment]
FIXME (not sure about my last statement)

**Comment by gre** [comment]
Fixed 262042c29837dbc3157e63c96ea7ce0990f5fcab

**Comment by kompot** [comment]
Could you please share code snippet of how to quit enumerating 'tail -f'.

Given `val log = CLI.enumerate("tail -f app.log")` how do to make sure that system process `tail` is killed on timeout.

Thanks in advance.
